-- =====================================================================
-- Configuração de campos por tenant + campos extras.
--
-- COMO RODAR:
--   Cole no SQL Editor do Supabase e execute. Idempotente (IF NOT EXISTS).
--   Não altera dados existentes.
--
-- Cobre:
--   1) Rótulos das categorias de cadastro por tenant (escopo='cadastro').
--   2) Visibilidade das colunas das tabelas Acordos/Mandados por tenant
--      (escopo='acordos' | 'mandados') + rótulo dos 2 campos extras.
--   3) % de honorários padrão por tenant (escopo='setting',
--      chave='porcentagem_honorarios_default').
--   + Duas colunas de texto livre em fin_acordos e fin_mandados (extra_1/2).
-- =====================================================================

-- ---------- Tabela genérica de configuração por tenant ----------
CREATE TABLE IF NOT EXISTS fin_campos_config (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant      text NOT NULL,
    escopo      text NOT NULL,              -- 'cadastro' | 'acordos' | 'mandados' | 'setting'
    chave       text NOT NULL,              -- ex.: 'fin_reu', 'reu', 'extra_1', 'porcentagem_honorarios_default'
    label       text NULL,                  -- rótulo custom (NULL = usa o padrão)
    valor       text NULL,                  -- usado por settings (ex.: % padrão)
    visivel     smallint NOT NULL DEFAULT 1,-- 0/1 (visibilidade da coluna na tabela)
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Uma linha por (tenant, escopo, chave).
CREATE UNIQUE INDEX IF NOT EXISTS uq_fin_campos_config
    ON fin_campos_config (tenant, escopo, chave);

CREATE INDEX IF NOT EXISTS ix_fin_campos_config_tenant_escopo
    ON fin_campos_config (tenant, escopo);

-- ---------- Campos extras (texto livre) ----------
ALTER TABLE fin_acordos
    ADD COLUMN IF NOT EXISTS extra_1 text NULL,
    ADD COLUMN IF NOT EXISTS extra_2 text NULL;

ALTER TABLE fin_mandados
    ADD COLUMN IF NOT EXISTS extra_1 text NULL,
    ADD COLUMN IF NOT EXISTS extra_2 text NULL;
