-- =====================================================================
-- Campos personalizados por tenant (substitui as 7 tabelas auxiliares
-- fixas: fin_status, fin_local, fin_conta, fin_reu, fin_uf,
-- fin_patrono_reu, fin_prazo_estimado).
--
-- ATENÇÃO — FAÇA BACKUP ANTES:
--   1) Supabase Dashboard → Project Settings → Database → Backups
--      → "Download backup" (gera um dump completo).
--   2) Ou via psql/pg_dump (instruções em docs/BACKUP.md).
--
-- COMO RODAR:
--   Cole no SQL Editor do Supabase e execute. Idempotente (IF NOT EXISTS
--   em tudo). Esta migration é 100% ADITIVA — não dropa nada, não altera
--   dados existentes. As tabelas legadas (fin_status, fin_local etc.)
--   continuam funcionando até a Fase 5 do refactor.
--
-- O QUE ELA FAZ:
--   1) Cria fin_custom_fields (até 10 campos personalizados por tenant).
--   2) Cria fin_custom_field_options (opções dos selects + cor/hierarquia).
--   3) Adiciona JSONB valores_custom em fin_acordos e fin_mandados
--      (para campos personalizados que não têm coluna fixa).
--   4) Adiciona coluna `ordem` em fin_campos_config (para reordenação
--      de colunas — Fase 3).
--   5) Faz seed dos 7 campos sistema (system_locked=1) para cada tenant
--      existente em fin_tenants, copiando as opções das tabelas legadas.
-- =====================================================================


-- ---------- 1) fin_custom_fields ----------
CREATE TABLE IF NOT EXISTS fin_custom_fields (
    id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant          text NOT NULL,
    chave           text NOT NULL,                   -- slug interno (ex: 'status', 'reu', 'cf_8')
    nome            text NOT NULL,                   -- rótulo exibido ao usuário (editável)
    tipo            text NOT NULL DEFAULT 'select_single',
                                                     -- 'texto' | 'numero' | 'data' | 'hora'
                                                     -- | 'select_single' | 'select_multi'
    ordem           int NOT NULL DEFAULT 100,        -- ordem dentro de cada escopo (Fase 3)
    escopo_acordos  smallint NOT NULL DEFAULT 1,     -- 0/1 — aparece em Acordos
    escopo_mandados smallint NOT NULL DEFAULT 1,     -- 0/1 — aparece em Mandados
    ativo           smallint NOT NULL DEFAULT 1,     -- 0/1
    system_locked   smallint NOT NULL DEFAULT 0,     -- 0/1 — bloqueia DELETE e mudança de tipo
                                                     -- (campos seedados pelo sistema)
    coluna_fixa     text NULL,                       -- se preenchido, valor vai p/ coluna fixa
                                                     -- em fin_acordos/fin_mandados; caso contrário
                                                     -- vai para valores_custom (JSONB).
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_fin_custom_fields_tenant_chave
    ON fin_custom_fields (tenant, chave);

CREATE INDEX IF NOT EXISTS ix_fin_custom_fields_tenant_ativo
    ON fin_custom_fields (tenant, ativo);


-- ---------- 2) fin_custom_field_options ----------
CREATE TABLE IF NOT EXISTS fin_custom_field_options (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant      text NOT NULL,
    field_id    bigint NOT NULL REFERENCES fin_custom_fields(id) ON DELETE CASCADE,
    valor       text NOT NULL,                       -- texto da opção (editável)
    cor         text NULL,                           -- cor de fundo (#RRGGBB) ou NULL
    cor_letra   text NOT NULL DEFAULT '#000000',     -- cor da letra
    hierarquia  smallint NOT NULL DEFAULT 5,         -- 1-10 (1 = maior prioridade na pintura)
    ativo       smallint NOT NULL DEFAULT 1,
    ordem       int NOT NULL DEFAULT 100,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT ck_hierarquia_1_10 CHECK (hierarquia BETWEEN 1 AND 10)
);

CREATE INDEX IF NOT EXISTS ix_fin_custom_field_options_field
    ON fin_custom_field_options (field_id, ativo);

CREATE INDEX IF NOT EXISTS ix_fin_custom_field_options_tenant
    ON fin_custom_field_options (tenant);

-- Mesmo valor não pode aparecer duas vezes no mesmo campo (case-insensitive).
CREATE UNIQUE INDEX IF NOT EXISTS uq_fin_custom_field_options_field_valor
    ON fin_custom_field_options (field_id, lower(valor));


-- ---------- 3) valores_custom (JSONB) em fin_acordos / fin_mandados ----------
ALTER TABLE fin_acordos
    ADD COLUMN IF NOT EXISTS valores_custom jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE fin_mandados
    ADD COLUMN IF NOT EXISTS valores_custom jsonb NOT NULL DEFAULT '{}'::jsonb;

-- Índice GIN para consultas/filtros em campos custom (performance).
CREATE INDEX IF NOT EXISTS ix_fin_acordos_valores_custom
    ON fin_acordos USING gin (valores_custom);

CREATE INDEX IF NOT EXISTS ix_fin_mandados_valores_custom
    ON fin_mandados USING gin (valores_custom);


-- ---------- 4) Coluna `ordem` em fin_campos_config (Fase 3) ----------
ALTER TABLE fin_campos_config
    ADD COLUMN IF NOT EXISTS ordem int NULL;


-- ---------- 5) Seed dos 7 campos sistema para cada tenant ----------
-- Cada bloco DO é idempotente: usa ON CONFLICT DO NOTHING.
--
-- Mapeamento (chave → label padrão, coluna fixa em fin_acordos/fin_mandados):
--   status         → 'Status'             → coluna 'status'
--   local          → 'Local'              → coluna 'local'
--   reu            → 'Réu'                → coluna 'reu'
--   uf             → 'UF'                 → coluna 'uf'
--   escritorio_reu → 'Patrono do réu'     → coluna 'escritorio_reu'
--                                            (originado de fin_patrono_reu)
--   prazo_estimado → 'Prazo estimado'     → coluna 'prazo_estimado'
--   conta          → 'Conta'              → SEM coluna fixa (JSONB)
--                                            (originado de fin_conta)

DO $$
DECLARE
    t_nome text;
BEGIN
    FOR t_nome IN SELECT nome FROM fin_tenants LOOP

        -- status
        INSERT INTO fin_custom_fields
            (tenant, chave, nome, tipo, ordem, system_locked, coluna_fixa)
        VALUES
            (t_nome, 'status', 'Status', 'select_single', 1, 1, 'status')
        ON CONFLICT (tenant, chave) DO NOTHING;

        -- local
        INSERT INTO fin_custom_fields
            (tenant, chave, nome, tipo, ordem, system_locked, coluna_fixa)
        VALUES
            (t_nome, 'local', 'Local', 'select_single', 2, 1, 'local')
        ON CONFLICT (tenant, chave) DO NOTHING;

        -- reu
        INSERT INTO fin_custom_fields
            (tenant, chave, nome, tipo, ordem, system_locked, coluna_fixa)
        VALUES
            (t_nome, 'reu', 'Réu', 'select_single', 3, 1, 'reu')
        ON CONFLICT (tenant, chave) DO NOTHING;

        -- uf (fin_uf é compartilhada entre tenants — usamos as opções globais
        -- mas criamos o campo por tenant para permitir renomear o label)
        INSERT INTO fin_custom_fields
            (tenant, chave, nome, tipo, ordem, system_locked, coluna_fixa)
        VALUES
            (t_nome, 'uf', 'UF', 'select_single', 4, 1, 'uf')
        ON CONFLICT (tenant, chave) DO NOTHING;

        -- escritorio_reu (originado de fin_patrono_reu)
        INSERT INTO fin_custom_fields
            (tenant, chave, nome, tipo, ordem, system_locked, coluna_fixa)
        VALUES
            (t_nome, 'escritorio_reu', 'Patrono do réu', 'select_single', 5, 1, 'escritorio_reu')
        ON CONFLICT (tenant, chave) DO NOTHING;

        -- prazo_estimado
        INSERT INTO fin_custom_fields
            (tenant, chave, nome, tipo, ordem, system_locked, coluna_fixa)
        VALUES
            (t_nome, 'prazo_estimado', 'Prazo estimado', 'select_single', 6, 1, 'prazo_estimado')
        ON CONFLICT (tenant, chave) DO NOTHING;

        -- conta (sem coluna fixa — vai para valores_custom JSONB)
        INSERT INTO fin_custom_fields
            (tenant, chave, nome, tipo, ordem, system_locked, coluna_fixa)
        VALUES
            (t_nome, 'conta', 'Conta', 'select_single', 7, 1, NULL)
        ON CONFLICT (tenant, chave) DO NOTHING;

    END LOOP;
END $$;


-- ---------- 6) Seed das opções a partir das tabelas legadas ----------
-- Copia linhas das 7 tabelas auxiliares para fin_custom_field_options.
-- Idempotente: usa ON CONFLICT DO NOTHING no índice único (field_id, lower(valor)).
--
-- Tabelas com cor/cor_letra/hierarquia: fin_status, fin_local, fin_conta.
-- Tabelas só com valor/ativo: fin_reu, fin_uf, fin_patrono_reu, fin_prazo_estimado.

-- status → fin_status
INSERT INTO fin_custom_field_options
    (tenant, field_id, valor, cor, cor_letra, hierarquia, ativo, ordem)
SELECT
    s.tenant,
    f.id,
    s.status,
    NULLIF(s.cor, ''),
    COALESCE(NULLIF(s.cor_letra, ''), '#000000'),
    COALESCE(GREATEST(1, LEAST(10, s.hierarquia)), 5),
    COALESCE(s.ativo, 1),
    100
FROM fin_status s
JOIN fin_custom_fields f
    ON f.tenant = s.tenant AND f.chave = 'status'
WHERE s.status IS NOT NULL AND s.status <> ''
ON CONFLICT (field_id, lower(valor)) DO NOTHING;

-- local → fin_local
INSERT INTO fin_custom_field_options
    (tenant, field_id, valor, cor, cor_letra, hierarquia, ativo, ordem)
SELECT
    l.tenant,
    f.id,
    l.local,
    NULLIF(l.cor, ''),
    COALESCE(NULLIF(l.cor_letra, ''), '#000000'),
    COALESCE(GREATEST(1, LEAST(10, l.hierarquia)), 5),
    COALESCE(l.ativo, 1),
    100
FROM fin_local l
JOIN fin_custom_fields f
    ON f.tenant = l.tenant AND f.chave = 'local'
WHERE l.local IS NOT NULL AND l.local <> ''
ON CONFLICT (field_id, lower(valor)) DO NOTHING;

-- conta → fin_conta
INSERT INTO fin_custom_field_options
    (tenant, field_id, valor, cor, cor_letra, hierarquia, ativo, ordem)
SELECT
    c.tenant,
    f.id,
    c.conta,
    NULLIF(c.cor, ''),
    COALESCE(NULLIF(c.cor_letra, ''), '#000000'),
    COALESCE(GREATEST(1, LEAST(10, c.hierarquia)), 5),
    COALESCE(c.ativo, 1),
    100
FROM fin_conta c
JOIN fin_custom_fields f
    ON f.tenant = c.tenant AND f.chave = 'conta'
WHERE c.conta IS NOT NULL AND c.conta <> ''
ON CONFLICT (field_id, lower(valor)) DO NOTHING;

-- reu → fin_reu (sem cor/hierarquia)
INSERT INTO fin_custom_field_options
    (tenant, field_id, valor, cor, cor_letra, hierarquia, ativo, ordem)
SELECT
    r.tenant,
    f.id,
    r.reu,
    NULL,
    '#000000',
    5,
    COALESCE(r.ativo, 1),
    100
FROM fin_reu r
JOIN fin_custom_fields f
    ON f.tenant = r.tenant AND f.chave = 'reu'
WHERE r.reu IS NOT NULL AND r.reu <> ''
ON CONFLICT (field_id, lower(valor)) DO NOTHING;

-- escritorio_reu → fin_patrono_reu (sem cor/hierarquia)
INSERT INTO fin_custom_field_options
    (tenant, field_id, valor, cor, cor_letra, hierarquia, ativo, ordem)
SELECT
    p.tenant,
    f.id,
    p.patrono_reu,
    NULL,
    '#000000',
    5,
    COALESCE(p.ativo, 1),
    100
FROM fin_patrono_reu p
JOIN fin_custom_fields f
    ON f.tenant = p.tenant AND f.chave = 'escritorio_reu'
WHERE p.patrono_reu IS NOT NULL AND p.patrono_reu <> ''
ON CONFLICT (field_id, lower(valor)) DO NOTHING;

-- prazo_estimado → fin_prazo_estimado (sem cor/hierarquia)
INSERT INTO fin_custom_field_options
    (tenant, field_id, valor, cor, cor_letra, hierarquia, ativo, ordem)
SELECT
    pe.tenant,
    f.id,
    pe.prazo_estimado,
    NULL,
    '#000000',
    5,
    COALESCE(pe.ativo, 1),
    100
FROM fin_prazo_estimado pe
JOIN fin_custom_fields f
    ON f.tenant = pe.tenant AND f.chave = 'prazo_estimado'
WHERE pe.prazo_estimado IS NOT NULL AND pe.prazo_estimado <> ''
ON CONFLICT (field_id, lower(valor)) DO NOTHING;

-- uf → fin_uf (TABELA COMPARTILHADA — não tem coluna tenant)
-- Insere as opções de UF para cada tenant existente.
INSERT INTO fin_custom_field_options
    (tenant, field_id, valor, cor, cor_letra, hierarquia, ativo, ordem)
SELECT
    f.tenant,
    f.id,
    u.uf,
    NULL,
    '#000000',
    5,
    COALESCE(u.ativo, 1),
    100
FROM fin_uf u
CROSS JOIN fin_custom_fields f
WHERE f.chave = 'uf'
  AND u.uf IS NOT NULL AND u.uf <> ''
ON CONFLICT (field_id, lower(valor)) DO NOTHING;


-- =====================================================================
-- FIM. Após rodar, valide com:
--   SELECT tenant, chave, nome, tipo, system_locked, ordem
--   FROM fin_custom_fields
--   ORDER BY tenant, ordem;
--
--   SELECT cf.tenant, cf.chave, COUNT(o.id) AS qtd_opcoes
--   FROM fin_custom_fields cf
--   LEFT JOIN fin_custom_field_options o ON o.field_id = cf.id
--   GROUP BY cf.tenant, cf.chave
--   ORDER BY cf.tenant, cf.chave;
--
-- Tabelas legadas (fin_status, fin_local, fin_conta, fin_reu, fin_uf,
-- fin_patrono_reu, fin_prazo_estimado) CONTINUAM existindo e funcionando.
-- Elas só serão descontinuadas após a Fase 5 do refactor.
-- =====================================================================
